/* --------------------------------------------------------------------------
   Unit tests for the optional JavaScript helpers.

   src/utils.js is optional but public: it ships in the package, it is
   documented, and until now nothing tested it. These cover the pure functions
   with no DOM. The helpers that touch the DOM belong in a browser harness --
   verify/*.html -- rather than here.

   Run with `npm test`. No dependencies: node:test and node:assert only.
   -------------------------------------------------------------------------- */

import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  animateValue,
  createCountSpans,
  cssVars,
  formatNumber,
  getEasing,
  staggerStyle,
  tm,
} from '../src/utils.js';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('formatNumber groups thousands and rounds', () => {
  assert.equal(formatNumber(1234567), '1,234,567');
  assert.equal(formatNumber(999), '999');
  assert.equal(formatNumber(1000), '1,000');
  assert.equal(formatNumber(1234.6), '1,235', 'rounds rather than truncating');
  assert.equal(formatNumber(1234567, ' '), '1 234 567', 'honours a custom separator');
  assert.equal(formatNumber(0), '0');
});

test('formatNumber keeps a negative sign outside the grouping', () => {
  assert.equal(formatNumber(-1234567), '-1,234,567');
});

test('getEasing returns named curves, and falls back rather than throwing', () => {
  assert.equal(getEasing('linear')(0.5), 0.5);
  assert.equal(getEasing('easeOutQuart')(0), 0);
  assert.equal(getEasing('easeOutQuart')(1), 1);
  assert.equal(getEasing('nonsense')(1), getEasing('easeOutExpo')(1));

  for (const name of ['linear', 'easeOutExpo', 'easeOutQuart', 'easeOutCubic', 'easeInOutQuad']) {
    const ease = getEasing(name);
    assert.equal(ease(0), 0, `${name} starts at 0`);
    assert.equal(ease(1), 1, `${name} lands exactly on 1`);
  }
});

test('createCountSpans wraps every character with its own stagger index', () => {
  const spans = createCountSpans('abc', { stagger: 40 });
  assert.equal(spans.length, 3);
  assert.deepEqual(spans[0], { char: 'a', index: 0, style: { '--tm-stagger': 0 }, delay: 0 });
  assert.equal(spans[2].delay, 80);
  assert.equal(createCountSpans('ab')[1].delay, 50, 'defaults to a 50ms step');
  assert.deepEqual(createCountSpans(''), [], 'empty text produces no spans');
});

test('createCountSpans keeps spaces, so words do not run together', () => {
  const spans = createCountSpans('a b');
  assert.equal(spans.length, 3);
  assert.equal(spans[1].char, ' ');
});

test('cssVars prefixes bare names and leaves explicit ones alone', () => {
  assert.deepEqual(cssVars({ duration: '300ms' }), { '--tm-duration': '300ms' });
  assert.deepEqual(cssVars({ '--custom': '1' }), { '--custom': '1' });
  assert.deepEqual(cssVars({}), {});
});

test('staggerStyle drives both container shapes from one call', () => {
  assert.deepEqual(staggerStyle(2, 75), {
    '--tm-stagger': 2,
    '--tm-stagger-index': 2,
    '--tm-delay': '150ms',
  });
  assert.equal(staggerStyle(0)['--tm-delay'], '0ms');
  assert.equal(staggerStyle(3)['--tm-delay'], '300ms', 'defaults to a 100ms step');
});

test('tm builds a class string from a behaviour and its modifiers', () => {
  assert.equal(tm('fade-in'), 'tm-fade-in');
  assert.equal(
    tm('pop', { duration: 300, delay: 75, repeat: 2, ease: 'snappy', distance: 8 }),
    'tm-pop tm-duration-300 tm-delay-75 tm-repeat-2 tm-ease-snappy tm-distance-8'
  );
  assert.equal(tm('pop', { duration: 0 }), 'tm-pop', 'a falsy modifier is dropped, not emitted');
});

/* The helper writes class names by hand. If a token group is ever renamed in
   the CSS, this is the test that fails instead of a silent no-op in someone's
   app. */
test('every class tm() can build exists in the built stylesheet', async () => {
  const css = await readFile(path.join(rootDir, 'tailmotion.css'), 'utf8');
  const built = tm('fade-in', {
    duration: 300,
    delay: 75,
    repeat: 2,
    ease: 'snappy',
    distance: 8,
    staggerStep: 75,
  });
  for (const className of built.split(' ')) {
    assert.ok(
      css.includes(`.${className}`),
      `${className} is generated by tm() but is not in tailmotion.css`
    );
  }
});

/* animateValue drives a browser frame loop. The tween arithmetic -- easing,
   range, the exact landing value, cancellation -- is plain JavaScript, so it is
   worth testing here with a frame scheduler standing in for the browser's. This
   is a test shim, not a claim that the helper runs outside a browser. */
const FRAME_MS = 16;
globalThis.requestAnimationFrame ??= (callback) =>
  setTimeout(() => callback(performance.now()), FRAME_MS);
globalThis.cancelAnimationFrame ??= (id) => clearTimeout(id);

test('animateValue reports the exact target and completes once', async () => {
  const seen = [];
  await new Promise((resolve) => {
    animateValue({
      from: 0,
      to: 100,
      duration: 40,
      easing: 'linear',
      onUpdate: (value) => seen.push(value),
      onComplete: resolve,
    });
  });
  assert.ok(seen.length > 1, 'reports intermediate values');
  assert.equal(seen.at(-1), 100, 'lands exactly on the target, never near it');
  assert.ok(
    seen.every((value) => value >= 0 && value <= 100),
    'never overshoots the range with a linear curve'
  );
});

test('animateValue can be cancelled before it finishes', async () => {
  let completed = false;
  const cancel = animateValue({
    from: 0,
    to: 100,
    duration: 400,
    onUpdate: () => {},
    onComplete: () => {
      completed = true;
    },
  });
  cancel();
  await new Promise((resolve) => setTimeout(resolve, 120));
  assert.equal(completed, false, 'a cancelled tween never calls onComplete');
});

test('animateValue counts down as well as up', async () => {
  const seen = [];
  await new Promise((resolve) => {
    animateValue({
      from: 50,
      to: 10,
      duration: 40,
      easing: 'linear',
      onUpdate: (value) => seen.push(value),
      onComplete: resolve,
    });
  });
  assert.equal(seen.at(-1), 10);
  assert.ok(seen[0] <= 50);
});
