/* Generated by scripts/check-render-cost.mjs. Do not edit by hand.
   Where each class does its per-frame work: compositor, filter, paint or
   layout. See docs/reference/render-cost.mdx. */
export const renderCost = {
  "tm-accordion-panel": {
    "tier": "layout",
    "loops": false
  },
  "tm-avatar": {
    "tier": "paint",
    "loops": false
  },
  "tm-avatar-tooltip": {
    "tier": "compositor",
    "loops": false
  },
  "tm-blur-in": {
    "tier": "filter",
    "loops": false
  },
  "tm-blur-out": {
    "tier": "filter",
    "loops": false
  },
  "tm-bounce": {
    "tier": "compositor",
    "loops": true
  },
  "tm-burst": {
    "tier": "compositor",
    "loops": false
  },
  "tm-confetti": {
    "tier": "compositor",
    "loops": false
  },
  "tm-count-reveal": {
    "tier": "compositor",
    "loops": false
  },
  "tm-dark-veil": {
    "tier": "filter",
    "loops": true
  },
  "tm-dark-veil-layer-1": {
    "tier": "compositor",
    "loops": true
  },
  "tm-dark-veil-layer-2": {
    "tier": "paint",
    "loops": true
  },
  "tm-dark-veil-layer-3": {
    "tier": "compositor",
    "loops": true
  },
  "tm-dark-veil-noise": {
    "tier": "compositor",
    "loops": true
  },
  "tm-drift": {
    "tier": "compositor",
    "loops": true
  },
  "tm-drop": {
    "tier": "compositor",
    "loops": false
  },
  "tm-elastic": {
    "tier": "compositor",
    "loops": false
  },
  "tm-fade-in": {
    "tier": "compositor",
    "loops": false
  },
  "tm-fade-out": {
    "tier": "compositor",
    "loops": false
  },
  "tm-feedback-button": {
    "tier": "compositor",
    "loops": false
  },
  "tm-fill-up": {
    "tier": "paint",
    "loops": false
  },
  "tm-flip-front": {
    "tier": "compositor",
    "loops": false
  },
  "tm-flip-hover": {
    "tier": "compositor",
    "loops": false
  },
  "tm-flip-x": {
    "tier": "compositor",
    "loops": false
  },
  "tm-flip-y": {
    "tier": "compositor",
    "loops": false
  },
  "tm-float": {
    "tier": "compositor",
    "loops": true
  },
  "tm-glide": {
    "tier": "compositor",
    "loops": false
  },
  "tm-glide-right": {
    "tier": "compositor",
    "loops": false
  },
  "tm-glow": {
    "tier": "compositor",
    "loops": true
  },
  "tm-hold-confirm": {
    "tier": "compositor",
    "loops": false
  },
  "tm-hold-delete": {
    "tier": "paint",
    "loops": false
  },
  "tm-hover-lift": {
    "tier": "paint",
    "loops": false
  },
  "tm-hover-scale": {
    "tier": "compositor",
    "loops": false
  },
  "tm-icon-swap": {
    "tier": "filter",
    "loops": false
  },
  "tm-lift-hover": {
    "tier": "paint",
    "loops": false
  },
  "tm-liquid-btn": {
    "tier": "paint",
    "loops": false
  },
  "tm-liquid-underline": {
    "tier": "layout",
    "loops": false
  },
  "tm-liquid-wave": {
    "tier": "layout",
    "loops": false
  },
  "tm-menu": {
    "tier": "compositor",
    "loops": false
  },
  "tm-morph": {
    "tier": "compositor",
    "loops": true
  },
  "tm-native-dialog": {
    "tier": "compositor",
    "loops": false
  },
  "tm-native-disclosure": {
    "tier": "layout",
    "loops": false
  },
  "tm-native-popover": {
    "tier": "compositor",
    "loops": false
  },
  "tm-number-swap": {
    "tier": "filter",
    "loops": false
  },
  "tm-pop": {
    "tier": "compositor",
    "loops": false
  },
  "tm-presence-fade": {
    "tier": "compositor",
    "loops": false
  },
  "tm-press": {
    "tier": "compositor",
    "loops": false
  },
  "tm-pulse": {
    "tier": "compositor",
    "loops": true
  },
  "tm-reveal": {
    "tier": "paint",
    "loops": false
  },
  "tm-ripple": {
    "tier": "compositor",
    "loops": true
  },
  "tm-rise": {
    "tier": "compositor",
    "loops": false
  },
  "tm-rotate-hover": {
    "tier": "compositor",
    "loops": false
  },
  "tm-rotate-in": {
    "tier": "compositor",
    "loops": false
  },
  "tm-rotate-press": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scale-fade": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scale-in": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scale-out": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scroll-fade": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scroll-progress": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scroll-reveal": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scroll-scale": {
    "tier": "compositor",
    "loops": false
  },
  "tm-scroll-slide-block": {
    "tier": "compositor",
    "loops": false
  },
  "tm-shake": {
    "tier": "compositor",
    "loops": false
  },
  "tm-shimmer": {
    "tier": "compositor",
    "loops": true
  },
  "tm-shimmer-hover": {
    "tier": "compositor",
    "loops": false
  },
  "tm-shimmer-text": {
    "tier": "paint",
    "loops": true
  },
  "tm-shimmer-text-sweep": {
    "tier": "compositor",
    "loops": true
  },
  "tm-slide-block-end": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-block-out": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-block-start": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-digit": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-inline-end": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-inline-out": {
    "tier": "compositor",
    "loops": false
  },
  "tm-slide-inline-start": {
    "tier": "compositor",
    "loops": false
  },
  "tm-sparkle": {
    "tier": "compositor",
    "loops": true
  },
  "tm-spin": {
    "tier": "compositor",
    "loops": true
  },
  "tm-stagger": {
    "tier": "filter",
    "loops": false
  },
  "tm-stagger-exit": {
    "tier": "filter",
    "loops": false
  },
  "tm-stream-text": {
    "tier": "filter",
    "loops": false
  },
  "tm-sway": {
    "tier": "compositor",
    "loops": true
  },
  "tm-swing-in": {
    "tier": "compositor",
    "loops": false
  },
  "tm-swing-in-left": {
    "tier": "compositor",
    "loops": false
  },
  "tm-swing-in-right": {
    "tier": "compositor",
    "loops": false
  },
  "tm-swing-out": {
    "tier": "compositor",
    "loops": false
  },
  "tm-swing-out-left": {
    "tier": "compositor",
    "loops": false
  },
  "tm-swing-out-right": {
    "tier": "compositor",
    "loops": false
  },
  "tm-tab-indicator": {
    "tier": "layout",
    "loops": false
  },
  "tm-text-flip-chars": {
    "tier": "filter",
    "loops": false
  },
  "tm-text-flip-word": {
    "tier": "filter",
    "loops": false
  },
  "tm-text-morph-word": {
    "tier": "filter",
    "loops": false
  },
  "tm-text-rotate-word": {
    "tier": "filter",
    "loops": false
  },
  "tm-unfold": {
    "tier": "compositor",
    "loops": false
  },
  "tm-view-morph": {
    "tier": "layout",
    "loops": false
  },
  "tm-wavy-bg": {
    "tier": "paint",
    "loops": true
  },
  "tm-wavy-bg-subtle": {
    "tier": "paint",
    "loops": true
  },
  "tm-wiggle": {
    "tier": "compositor",
    "loops": false
  },
  "tm-zoom-in": {
    "tier": "compositor",
    "loops": false
  },
  "tm-zoom-in-slow": {
    "tier": "compositor",
    "loops": false
  },
  "tm-zoom-out": {
    "tier": "compositor",
    "loops": false
  }
};
